[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[theme]
primaryColor = "#00BFFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#222222"
font = "sans serif"